### ISSUE TITLE
X-org Error

### ISSUE THREAD

**Issue by Ravenext** [Re4son/WSL-Kali-X#4]
> (EE)
> Fatal server error:
> (EE) parse_vt_settings: Cannot open /dev/tty0 (Permission denied)
> (EE)
> (EE)

This error appears whenever i use
`~/start-xfce`

**Comment by Re4son** [comment]
Not sure yet what causes it but it only seems to happen immediately after installation. Just close the bash window, open Kali again and run ~/start-xfce. That should do the trick.

I haven't had that before but I could reproduce it now with a newly installed Kali and Voodoo. I'll investigate further. Please let me know if the above step doesn't work.

Many thanks,
Re4son

**Comment by Ravenext** [comment]
Well, I installed Dbus and it seems your suggestion to re-open it somehow fixed it. Now i have to install kali-linux-full for the time being.
